# Generated by Django 3.1.4 on 2020-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Местоположение'),
        ),
    ]
