# Generated by Django 3.1.4 on 2020-12-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20201223_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred', to=settings.AUTH_USER_MODEL, verbose_name='Ссылка наставника'),
        ),
    ]
