# Generated by Django 3.1.4 on 2020-12-24 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_referralcodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcodes',
            options={'ordering': ('user', 'code'), 'verbose_name': 'Реферальный код', 'verbose_name_plural': 'Реферальная система'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Баланс'),
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_consideration', models.PositiveIntegerField(verbose_name='На рассмотрении')),
                ('available', models.PositiveIntegerField(verbose_name='Средства на балансе')),
                ('reserved', models.PositiveIntegerField(verbose_name='Зарезервировано к выплате')),
                ('paid_out', models.PositiveIntegerField(verbose_name='Выплачено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
                'ordering': ('user', 'available'),
            },
        ),
    ]
