# Generated by Django 3.1.4 on 2020-12-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201225_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники программы'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='profiles.money', verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.SlugField(max_length=30, verbose_name='Реферальная ссылка'),
        ),
    ]
