# Generated by Django 3.1.4 on 2021-01-09 11:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201225_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referrer',
            field=models.CharField(max_length=30, verbose_name='Реферальная ссылка'),
        ),
    ]
