# Generated by Django 3.1.5 on 2021-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Статус'),
        ),
    ]
