# Generated by Django 3.1.5 on 2021-01-21 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Зарезервированная сумма')),
                ('is_paid_out', models.BooleanField(default=False, verbose_name='Выплачено?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ('created_at',),
            },
        ),
    ]
