# Generated by Django 3.1.5 on 2021-01-23 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0015_applicationsformoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveIntegerField(max_length=16, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карта для вывода средств',
                'verbose_name_plural': 'Карты для вывода средств',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Cards', verbose_name='Карты'),
        ),
    ]
