# Generated by Django 3.1.5 on 2021-01-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210123_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
