# Generated by Django 3.1.5 on 2021-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210123_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(blank=True, to='profiles.Cards', verbose_name='Карты'),
        ),
    ]
