# Generated by Django 3.1.5 on 2021-01-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210123_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cards',
        ),
    ]
