# Generated by Django 3.1.5 on 2021-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_profile_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsformoney',
            name='card',
            field=models.CharField(default=1, max_length=16, verbose_name='На карту'),
            preserve_default=False,
        ),
    ]
