# Generated by Django 3.1.5 on 2021-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_applicationsformoney_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsformoney',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано?'),
        ),
    ]
