# Generated by Django 3.1.5 on 2021-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_applicationsformoney_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Начислено'),
        ),
        migrations.AlterField(
            model_name='money',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Средства на балансе'),
        ),
        migrations.AlterField(
            model_name='money',
            name='paid_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Выплачено'),
        ),
        migrations.AlterField(
            model_name='money',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Зарезервировано к выплате'),
        ),
        migrations.AlterField(
            model_name='money',
            name='under_consideration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='На рассмотрении'),
        ),
    ]
