# Generated by Django 3.1.5 on 2021-02-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_feedbackrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackrequests',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Сообщения обратной связи'},
        ),
    ]
