# Generated by Django 3.1.5 on 2021-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20210203_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodes',
            name='qr_code',
            field=models.FileField(blank=True, upload_to='qr_code'),
        ),
    ]
