# Generated by Django 3.1.5 on 2021-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20210204_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcodes',
            name='qr_code',
            field=models.BooleanField(default=False, editable=False, verbose_name='QR код'),
        ),
    ]
