# Generated by Django 3.1.5 on 2021-02-08 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0030_auto_20210204_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='struct1',
            field=models.ManyToManyField(blank=True, related_name='struct_1', to=settings.AUTH_USER_MODEL, verbose_name='Уровень 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='struct2',
            field=models.ManyToManyField(blank=True, related_name='struct_2', to=settings.AUTH_USER_MODEL, verbose_name='Уровень 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='struct3',
            field=models.ManyToManyField(blank=True, related_name='struct_3', to=settings.AUTH_USER_MODEL, verbose_name='Уровень 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='struct4',
            field=models.ManyToManyField(blank=True, related_name='struct_4', to=settings.AUTH_USER_MODEL, verbose_name='Уровень 4'),
        ),
        migrations.AddField(
            model_name='profile',
            name='struct5',
            field=models.ManyToManyField(blank=True, related_name='struct_5', to=settings.AUTH_USER_MODEL, verbose_name='Уровень 5'),
        ),
    ]
