# Generated by Django 3.1.5 on 2021-02-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20210208_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Системные сообщения', 'verbose_name_plural': 'Системные сообщения'},
        ),
    ]
