# Generated by Django 3.1.5 on 2021-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20210213_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.TextField(blank=True, null=True, verbose_name='Действие'),
        ),
    ]
