# Generated by Django 3.1.5 on 2021-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20210213_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodes',
            name='struct',
            field=models.IntegerField(default=1, verbose_name='Структура'),
        ),
    ]
