# Generated by Django 3.1.5 on 2021-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_referralcodes_struct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcodes',
            name='struct',
        ),
        migrations.AddField(
            model_name='profile',
            name='struct',
            field=models.IntegerField(default=1, verbose_name='Структура'),
        ),
    ]
