# Generated by Django 3.1.5 on 2021-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20210224_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='self_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Личный зароботок. Средства на балансе'),
        ),
        migrations.AddField(
            model_name='money',
            name='self_under_consideration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Личный зароботок. На рассмотрении'),
        ),
        migrations.AddField(
            model_name='profile',
            name='broker',
            field=models.BooleanField(default=0, verbose_name='Статус брокера'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referrals_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
