# Generated by Django 3.1.5 on 2021-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20210302_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='broker_status',
            field=models.IntegerField(default=0, verbose_name='Статус вывода средств для брокера'),
        ),
    ]
