# Generated by Django 3.1.5 on 2021-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_remove_profile_referrals_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='broker',
        ),
        migrations.AddField(
            model_name='profile',
            name='referrals_counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='broker_status',
            field=models.IntegerField(default=0, verbose_name='Статус брокера'),
        ),
    ]
