# Generated by Django 3.1.5 on 2021-03-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20210302_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='broker_status',
            field=models.BooleanField(default=False, verbose_name='Статус брокера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referrals_counts',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество активных рефералов'),
        ),
    ]
