# Generated by Django 3.1.5 on 2021-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_auto_20210302_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='broker',
            field=models.BooleanField(default=False, verbose_name='Статус брокера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='broker_status',
            field=models.BooleanField(default=False, verbose_name='Вывод средств с личных продаж'),
        ),
    ]
