# Generated by Django 3.1.5 on 2021-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20210302_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referrals_counts',
            field=models.IntegerField(default=0, verbose_name='Количество активных рефералов'),
        ),
    ]
