# Generated by Django 3.1.5 on 2021-03-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20210302_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Сумма'),
        ),
    ]
