# Generated by Django 3.1.5 on 2021-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='slug',
            field=models.CharField(max_length=250, verbose_name='Ссылка'),
        ),
    ]
