# Generated by Django 3.1.5 on 2021-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210130_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfo',
            name='decision',
        ),
        migrations.AddField(
            model_name='mfo',
            name='sum',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма займа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mfo',
            name='percents',
            field=models.FloatField(verbose_name='Ставка займа'),
        ),
    ]
