# Generated by Django 3.1.5 on 2021-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210203_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен'),
        ),
    ]
