# Generated by Django 3.1.5 on 2021-02-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210203_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
