# Generated by Django 3.1.5 on 2021-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210203_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='demands',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='credits',
            name='documents',
            field=models.CharField(max_length=250, verbose_name='Требуемые документы'),
        ),
    ]
