# Generated by Django 3.1.5 on 2021-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210203_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rko',
            name='cash_withdrawal',
            field=models.FloatField(verbose_name='Снятие наличных'),
        ),
        migrations.AlterField(
            model_name='rko',
            name='service_cost',
            field=models.FloatField(verbose_name='Стоимость обслуживания'),
        ),
    ]
