# Generated by Django 3.1.5 on 2021-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210203_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idorders',
            name='order_id',
            field=models.CharField(max_length=250, unique=True, verbose_name='ID Отчета'),
        ),
    ]
