# Generated by Django 3.1.5 on 2021-02-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210213_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refinancing',
            options={'ordering': ('bank_name', 'type'), 'verbose_name': 'Рифенансирование', 'verbose_name_plural': 'Рефинансирование'},
        ),
        migrations.AlterModelOptions(
            name='rko',
            options={'ordering': ('bank_name',), 'verbose_name': 'Рассчетно кассовое обслуживание', 'verbose_name_plural': 'Рассчетно кассовое обслуживание '},
        ),
    ]
