# Generated by Django 3.1.5 on 2021-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210224_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='referral_slug_2',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Реферальная ссылка на продукт 2'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='referral_slug',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Реферальная ссылка на продукт 1'),
        ),
    ]
