# Generated by Django 3.1.5 on 2021-03-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_auto_20210303_1309'),
        ('web', '0013_auto_20210224_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='idorders',
            name='broker',
            field=models.BooleanField(default=False, verbose_name='Брокерская заявка'),
        ),
        migrations.AddField(
            model_name='idorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Пользователь'),
        ),
    ]
