# Generated by Django 3.1.5 on 2021-03-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210313_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcards',
            options={'ordering': ('-recommend', 'bank_name', 'card_name'), 'verbose_name': 'Кредитная карта', 'verbose_name_plural': 'Кредитные карты'},
        ),
        migrations.AlterModelOptions(
            name='credits',
            options={'ordering': ('-recommend', 'bank_name', 'type'), 'verbose_name': 'Кредит', 'verbose_name_plural': 'Кредиты'},
        ),
        migrations.AlterModelOptions(
            name='debitcards',
            options={'ordering': ('-recommend', 'bank_name', 'card_name'), 'verbose_name': 'Дебетовая карта', 'verbose_name_plural': 'Дебетовые карты'},
        ),
        migrations.AlterModelOptions(
            name='mfo',
            options={'ordering': ('-recommend', 'bank_name'), 'verbose_name': 'Микрозайм', 'verbose_name_plural': 'Микрозаймы'},
        ),
        migrations.AlterModelOptions(
            name='mortgages',
            options={'ordering': ('-recommend', 'bank_name', 'type'), 'verbose_name': 'Ипотечный кредит', 'verbose_name_plural': 'Ипотечные кредиты'},
        ),
        migrations.AlterModelOptions(
            name='potrebcredits',
            options={'ordering': ('-recommend', 'bank_name', 'type'), 'verbose_name': 'Потребительский кредит', 'verbose_name_plural': 'Потребительские кредиты'},
        ),
        migrations.AlterModelOptions(
            name='refinancing',
            options={'ordering': ('-recommend', 'bank_name', 'type'), 'verbose_name': 'Рифенансирование', 'verbose_name_plural': 'Рефинансирование'},
        ),
        migrations.AlterModelOptions(
            name='rko',
            options={'ordering': ('-recommend', 'bank_name'), 'verbose_name': 'Рассчетно кассовое обслуживание', 'verbose_name_plural': 'Рассчетно кассовое обслуживание '},
        ),
    ]
